---
title: "DataFest"
author: "Albert Sun and Ben Wallace"
date: "4/9/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r upload packages, results = "hide"}
library(dplyr)
library(ggplot2)
library(patchwork)
library(twitteR)
library(lubridate)
library(rvest)
library(sf)
library(tidycensus)
library(leaflet)
library(mapview)
library(broom)
```

```{r read files, results = "hide"}
counties <- read.csv("datafiles/us-counties.csv")
states <- read.csv("datafiles/us-states.csv")
measures <- read.csv("datafiles/statedata.csv")
global_measures <- read.csv("datafiles/ACAPSGlobalResponse.csv")
covidapproval <- read.csv("datafiles/Covidapproval_Population.csv")
jails <- read.csv("datafiles/DataFest Covid in Jails - Sheet1.csv")
```

```{r topten}
toptencounties <- counties %>%
  filter(date == "2020-04-08") %>%
  arrange(desc(cases))
  
toptencounties <- toptencounties[1:10,]

toptenstates <- states %>%
  filter(date == "2020-04-08") %>%
  arrange(desc(cases))

toptenstates <- toptenstates[1:10,]
```

# NY State and County Date

```{r plot}
p1 <- ggplot(data = toptencounties, mapping = aes(x = reorder(county, cases), y = cases), fill=if_else(County=="New York")) +
  geom_bar(stat = "identity") + 
  labs(title = "Top 10 Coronavirus counties cases", 
       y = "Cases", x = "County Name") + 
  coord_flip()

p2 <- ggplot(data = toptenstates, mapping = aes(x = reorder(state, cases), y = cases)) +
  geom_bar(stat = "identity") + 
  labs(title = "Top 10 Coronavirus states cases", 
       y = "Cases", x = "State Name") + 
  coord_flip() 

p1 + p2
```

# State First Stay at Home

```{r addmeasures} 
### Removing United States from df

measures <- measures[-c(1),]

dates <- c("4/4/2020 17:00", # Dates of stay at home orders
           "3/28/2020 17:00",
           "3/31/2020 17:00",
           "",
           "3/19/2020 0:00",
           "3/26/2020 6:00",
           "3/23/2020 20:00",
           "3/24/2020 8:00",
           "4/1/2020 0:01",
           "4/3/2020 0:01",
           "4/3/2020 0:00",
           "3/25/2020 0:01",
           "3/25/2020 13:30",
           "3/21/2020 17:00",
           "3/24/2020 23:59",
           "",
           "3/30/2020 0:01",
           "3/26/2020 20:00",
           "3/23/2020 17:00",
           "4/2/2020 0:01",
           "3/30/2020 20:00",
           "3/23/2020 12:00",
           "3/24/2020 0:01",
           "3/27/2020 23:59",
           "4/3/2020 17:00",
           "4/6/2020 0:01",
           "3/28/2020 0:01",
           "",
           "4/1/2020 0:00",
           "3/27/2020 23:59",
           "3/21/2020 21:00",
           "3/24/2020 8:00",
           "3/22/2020 20:00",
           "3/30/2020 15:00",
           "",
           "3/23/2020 23:59",
           "",
           "3/23/2020 0:00",
           "4/1/2020 20:00",
           "3/28/2020 0:00",
           "4/7/2020 17:00",
           "",
           "3/31/2020 23:59",
           "4/2/2020 0:01",
           "",
           "3/25/2020 17:00",
           "3/30/2020 0:00",
           "3/23/2020 0:00",
           "3/24/2020 20:00",
           "3/25/2020 8:00",
           ""
           )

### Adding data to measures df
measures <- measures %>%
  mutate(date.stay.at.home = dates)  %>%
  mutate(stateno = c(1:51))

```

```{r plotstayathome}
### Plot of stay at home dates

measures$date.stay.at.home = as.Date(measures$date.stay.at.home, "%m/%d/%y")
med <- median(measures$date.stay.at.home, na.rm = TRUE)
avg <- mean(measures$date.stay.at.home, na.rm = TRUE)

ggplot(data = measures, aes(x = date.stay.at.home)) +
         geom_histogram(stat = "count") +
   scale_x_date(breaks = "3 days") +
  theme(axis.text.x = element_text(angle = 90)) + 
  geom_vline(xintercept = med, color = "darkred") +
  geom_vline(xintercept = avg, color = "navy")

```

# Twitter

TwitteR:

https://opensource.com/article/17/6/collecting-and-mapping-twitter-data-using-r

**I'm still applying for a Twitter dev account in order to access the Twitter API**

# Global Measures

```{r countries_most_social_distancing}
global_measures %>%
  filter(CATEGORY == "Social distancing") %>%
  count(COUNTRY) %>%
  arrange(-n)
```

First Social Distancing Measure From top-10 quickest and top-10 slowest Country 
to test responsiveness:

```{r convert_dates_to_ordered_lubridate}
first_measures <- global_measures %>%
  filter(CATEGORY == "Social distancing") %>%
  mutate(date = dmy(DATE_IMPLEMENTED)) %>%
  arrange(COUNTRY, date) %>%
  select(COUNTRY, date) %>%
  group_by(COUNTRY) %>%
  slice(1) %>%
  ungroup() %>%
  select(COUNTRY, date) %>%
  arrange(date) %>%
  slice(-11:-n()-10)
```

```{r top_bottom_10_reactions}
ggplot(first_measures, mapping = aes(x = reorder(COUNTRY, date), y = date)) +
  geom_point() + coord_flip() + 
  labs(y = "1st Social Distancing Measure Date", x = "Country",
       title = "1st Social Distancing Implemented") + 
  theme_minimal(base_size = 14)
```

# RVest

```{r Webscraping}
civiqs_poll <- "https://civiqs.com/results/approve_president_trump?annotations=true&uncertainty=true&zoomIn=true"
html <- read_html(civiqs_poll)

characters <- html_text(html, ".iLEVuK:nth-child(9) .blyETw:nth-child(1) , .iLEVuK:nth-child(9) .kTXupV:nth-child(1) , .iLEVuK:nth-child(9) .eafFIQ")
```



# Jail Data

```{r Overview of Data}
jails %>%
  summarise(n(), n_distinct(State)) 
```

We have data from 334 counties from 27 states.

```{r}
topTenJails <- jails %>%
  arrange(Percentage.Change) %>%
  select(State, County, Percentage.Change) %>%
  slice(1:10)

ggplot(data = topTenJails, mapping = aes(x = reorder(County, Percentage.Change), 
                                         y = abs(Percentage.Change) * 100)) + 
  geom_bar(stat = "identity") +
  coord_flip() + 
  labs(x = "County", y = "Percent Decrease in Prisons", 
       title = "Top Ten Drops in Incarceration Rates in County Jails") 
```

```{r bunch_of_graphs}
ggplot(data = jails, aes(x = Percentage.Change)) +
  geom_histogram()

ggplot(data = jails, aes(x = County.Profile)) +
  geom_histogram(binwidth = .025)

ggplot(data = jails, aes(x = State.Profile)) +
geom_histogram(binwidth = 5)

jails$Jurisdiction.Profile = jails$Jurisdiction.Profile..R.B.M.

ggplot(data = jails, aes(x = Jurisdiction.Profile)) +
  geom_bar()

ggplot(data = jails, aes(x = Jail.Incarceration.Rate.Per.100K)) +
geom_histogram()

ggplot(data = jails, aes(x = COVID.19.Cases)) +
  geom_histogram()

jails %>%
  summarise(mean = mean(COVID.19.Cases), ## Also log transform this?
            median = median(COVID.19.Cases)
  )

ggplot(data = jails, aes(x = log(Deaths.Per.100K.Residents))) + ### Log transform variable?
  geom_histogram()

```

```{r model fitting}
lm_full <- lm(Percentage.Change ~ County.Profile + State.Profile + Jurisdiction.Profile, data = jails)

lm <- step(lm_full, direction = "backward", trace=FALSE) 

tidy(lm) %>%
  select(term, estimate, p.value)

```

```{r diagnostic_plots}
plot_diagnostic <- function(x, data) {
  
  plot_variance <- augment(x) %>%
    ggplot(aes(x = .fitted, y = .resid)) +
    geom_point() + 
    geom_hline(yintercept = 0, color = "blue", lty = 2) +
    labs(x = expression(hat(y)), y = "Residual Value", 
         title = "Variance Plot") 
  
  plot_normality <- augment(x) %>%
    ggplot(aes(x = .resid)) +
    geom_histogram(binwidth = .01, alpha = .5, color = "orange") + 
    labs(x = "Residual Value", y = "Count", title = "Normality Plot") 
  
  plot_independence <- augment(x) %>%
    ggplot(aes(x = 1:nrow(data), y = .resid)) + 
    geom_point() + 
    labs(x = "Index", y = "Residual Value", title = "Independence Plot") 
  
  plot_variance / (plot_normality + plot_independence)
}

plot_diagnostic(lm, jails)
```

# Trump approval Ratings

```{r} 

### Plot of Trump approval rona vs. non-rona

#covidapproval$State = covidapproval$ï..State

#ggplot(data = covidapproval, aes(x = reorder(State, TrumpCOVID))) +
#  geom_bar(stat = "identity", aes(y = TrumpCOVID), fill = "red", color = "red", alpha = 0.2) +
#  geom_point(stat = "identity", aes(y = Trumpapprov), color = "black") +
#  theme(axis.text.x = element_text(angle = 90)) +
#  labs(x = "State",
#       y = "Percent Approval",
#       title = "Trump 'Rona and non-'Rona Approval") +
#  theme(axis.text.x = element_text(angle = 90)) + 
#  labs(title = "Trump Approval Ratings vs. Without", x = "State",
#       y = "Approval Rating") + 
#  theme(legend.position="right")
```