---
title: "Jails"
author: "Albert Sun and Ben Wallace"
date: "4/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r upload packages, results = "hide"}
library(dplyr)
library(knitr)
library(ggplot2)
library(patchwork)
library(twitteR)
library(lubridate)
library(rvest)
library(sf)
library(tidycensus)
library(mapview)
library(broom)
library(tidyverse)       # Tidyverse for Tidy Data
library(readxl)
library(tigris)
library(sf)
library(viridis)
library(stringr)
library(maps)
```

```{r read files, results = "hide"}
jails <- read.csv("datafiles/Jails.finalstates.csv")
lajails <- read.csv("datafiles/la_incarceration.csv")
```

```{r Overview of Data}
jails %>%
  summarise(n(), n_distinct(State_Abbrev)) 
```

We have data from 334 counties from 27 states.

# Data Wrangling

```{r Filter to LA jails}
jails <- jails %>%
  filter(State == "Louisiana")
```

```{r Remove "parish" from name}
lajails$county_name = str_replace(lajails$county_name, " Parish", "")
```

```{r join data}

lajails$county_name = as.factor(lajails$county_name)

jails <- left_join(jails, lajails, by = c("County" = "county_name"))
```

```{r recode private prison}
jails$private_jail_flag = as.factor(jails$private_jail_flag)
```

```{r jail demographics}
jails <- jails %>%
  mutate(pctblackjail = (black_jail_pop)/(total_jail_pop) * 100) %>%
  mutate(pctlatinxjail = (latinx_jail_pop)/(total_jail_pop) * 100) %>%
  mutate(pctwhitejail = (white_jail_pop)/(total_jail_pop) * 100) %>%
  mutate(pctpretrial = (total_jail_pretrial)/(total_jail_pop) * 100) %>%
  mutate(pctprison = (total_jail_from_prison)/(total_jail_pop) * 100) %>%
  mutate(pctjailfromother = (total_jail_from_other_jail)/(total_jail_pop) * 100) %>%
  mutate(pctcapacity = (jail_rated_capacity)/(total_jail_pop) * 100)
```

# Top Ten Drops

```{r top-ten-drops}
theme_set(theme_bw())

topTenJails <- jails %>%
  filter(State == "Louisiana") %>%
  arrange(Percent_Change) %>%
  mutate(percent_needed = Target_Jail_Population / Jail_Population_Latest * 100) %>%
  select(County, percent_needed, PreCovid_Jail_Pop) %>%
  slice(1:10) 
topTenJails

Int_Plot <- ggplot(topTenJails, aes(x = reorder(County, PreCovid_Jail_Pop), 
                                    y = percent_needed)) +
  geom_col() + 
  coord_flip() + 
  labs(x = "Jails w/ Biggest Pop. Reduction", y = "Percent (%) Decrease Still Needed
to Match International Norms",
  title = "Over-Incarceration Still Exists in Louisiana 
After Jails Release People Early for COVID-19") + 
  theme_classic(base_size = 16)

Int_Plot

```

# Slope

```{r slope-chart}
#top ten jail decreases with initial jail population >50
topTenJails <- jails %>%
  arrange(Percent_Change) %>%
  filter(State == "Louisiana") %>%
  filter(PreCovid_Jail_Pop > 50) %>%
  select(CountyState, County, Percent_Change, PreCovid_Jail_Pop, Jail_Population_Latest) %>%
  slice(1:10) %>%
  arrange(-PreCovid_Jail_Pop) %>%
  mutate(class = ifelse(Jail_Population_Latest-PreCovid_Jail_Pop >= 0, "red", "green"))
         
topTenJails

left_label <- c(paste(topTenJails$County, topTenJails$PreCovid_Jail_Pop, sep=", ")[1:3],character(7))
right_label <- c(paste(topTenJails$County, topTenJails$Jail_Population_Latest,sep=", ")[1:3],character(7))

library(scales)
theme_set(theme_classic())
p <- ggplot(topTenJails) + 
  geom_segment(aes(x=1, xend=2, y=PreCovid_Jail_Pop, yend=Jail_Population_Latest, col=class), size=.75, show.legend=F) + 
  geom_vline(xintercept=1, linetype="dashed", size=.1) + 
  geom_vline(xintercept=2, linetype="dashed", size=.1) +
  scale_color_manual(labels = c("Up", "Down"), 
                     values = c("green"="#00ba38", "red" = "#f8766d")) +  # color of lines
  xlim(0.5,2.5) +
  ylim(0,1100) + 
  labs(x="", 
       y="# People in Jail", 
       title = "Slope Chart: Top Ten Jail 
Population Decreases in Louisiana",
       caption = "Counties Not Labelled: Washington, Jackson, 
Concordia, Vernon, Allen, De Soto, Catahoula") + 
  theme_classic(base_size = 16)

p <- p + geom_text(label=left_label, y=topTenJails$PreCovid_Jail_Pop+10, x=rep(1, NROW(topTenJails)), hjust=1.1, size=3.5)
p <- p + geom_text(label=right_label, y=topTenJails$Jail_Population_Latest, x=rep(2, NROW(topTenJails)), hjust=-0.1, size=3.5)


p <- p + geom_text(label="Before
           COVID-19", x=1, y=1.12*(max(topTenJails$PreCovid_Jail_Pop, topTenJails$Jail_Population_Latest)), hjust=1, size=5.5)  # title
p <- p + geom_text(label="4/9/2020", x=2, y=1.12*(max(topTenJails$PreCovid_Jail_Pop, topTenJails$Jail_Population_Latest)), hjust=-0.1, size=5.5)  # title


p <- p + theme(panel.background = element_blank(), 
           panel.grid = element_blank(),
           axis.ticks = element_blank(),
           axis.text.x = element_blank(),
           panel.border = element_blank(),
           plot.margin = unit(c(1,2,1,2), "cm"))

p
```


# EDA 

```{r state racial composition}

blackpop <- c("P005004")

blackgeo <- get_decennial(geography = "county", variables = blackpop, year = 2010, summary_var = "P001001", geometry = TRUE, state = "LA") %>%
  mutate(pctblack = 100 * (value / summary_value))

jails$CountyState = as.character(jails$CountyState)
blackgeo$NAME = str_replace(blackgeo$NAME, " Parish", "")

jails <- left_join(jails, blackgeo, by = c("CountyState" = "NAME"))

stategeo <- st_as_sf(map("state", plot = FALSE, fill = TRUE, state = "LA")) %>%
  filter(ID == "louisiana") 

jails$geom = jails$geometry

```

```{r Percent black}

ggplot() +
  geom_sf(aes(geometry = geom, fill = pctblack, color = pctblack), data = jails) +
  labs(title = "Percent Black by Parish",
       fill = "Percent Black",
       color = "Percent Black",
       caption = "Parishes excluded:") + 
  scale_fill_viridis(option = "viridis") + 
  scale_color_viridis(option = "viridis") +
  geom_sf(data = stategeo, fill = NA) +
  theme(panel.background = element_rect(fill = "white"),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank()) 
```

```{r Judicial profiles}
### Mapping Jurisdictions

jails$Jurisdiction_Profile = recode_factor(jails$Jurisdiction_Profile, "R" = "Conservative", "M" = "Moderate", "B" = "Liberal")

ggplot() +
  geom_sf(aes(geometry = geom, fill = Jurisdiction_Profile), data = jails) +
  labs(title = "Jurisdiction Profile",
       fill = "Jurisdiction Profile") + 
  geom_sf(data = stategeo, fill = NA) +
  scale_fill_manual(values = c("darkred", "forestgreen", "blue2")) +
  theme(panel.background = element_rect(fill = "white"),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank()) 
```

```{r Percent change}
ggplot() +
  geom_sf(aes(geometry = geom, fill = Percent_Change, color = Percent_Change), data = jails) +
  labs(title = "Percent Change by Parish",
       fill = "Percent Change",
       color = "Percent Change",
       caption = "Parishes excluded:") + 
  scale_fill_viridis(option = "viridis") + 
  scale_color_viridis(option = "viridis") +
  geom_sf(data = stategeo, fill = NA) +
  theme(panel.background = element_rect(fill = "white"),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank()) 
```

```{r }
ggplot() +
  geom_sf(aes(geometry = geom, fill = pctblackjail, color = pctblackjail), data = jails) +
  labs(title = "Percent of Prison Population Black",
       fill = "Percent Black",
       color = "Percent Black",
       caption = "Parishes excluded:") + 
  scale_fill_viridis(option = "viridis") + 
  scale_color_viridis(option = "viridis") +
  geom_sf(data = stategeo, fill = NA) +
  theme(panel.background = element_rect(fill = "white"),
        axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks = element_blank()) 
```

## Univariate EDA

```{r Reponse variable}
jails <- jails %>%
  mutate(ab_avg = Percent_Change < -.2)
```

```{r bunch_of_graphs, echo=FALSE}
p1 <- ggplot(data = jails, aes(x = Percent_Change)) +
  geom_histogram(binwidth = 0.05, fill = "skyblue", color = "black") +
  labs(x = "Percent Change",
       y = "Frequency",
       title = "Percent Change") +
  geom_vline(xintercept = -.2, color = "darkred")

p2 <- ggplot(data = jails, aes(x = County_Profile)) +
  geom_histogram(binwidth = .025, color = "black", fill = "honeydew") + 
  labs(title = "County Profile",
       x = "Percentage won by Trump (2016)",
       y = "Frequency")

p3 <- ggplot(data = jails, aes(x = Jurisdiction_Profile)) +
  geom_bar(color = "black", fill = "tomato") +
  labs(title = "Jurisdiction Profile",
       x = "Jurisdiction Profile",
       y = "Frequency")

p4 <- ggplot(data = jails, aes(x = urbanicity)) +
geom_bar(fill = "navy", color = "black") +
  labs(title = "Population Density",
       x = "Type",
       y = "Frequency")

p5 <- ggplot(data = jails, aes(x = COVID.19_Cases)) +
  geom_histogram(fill = "white", color = "black", binwidth = 40) +
  labs(title = "COVID.19 Cases",
       x = "Number of Cases",
       y = "Frequency")

jails %>%
  summarise(mean = mean(COVID.19_Cases), 
            median = median(COVID.19_Cases))

p6 <- ggplot(data = jails, aes(x = COVID.19_Deaths)) + 
  geom_histogram(fill = "orange2", color = "black", binwidth = 10) +
  labs(title = "COVID.19 Deaths",
       x = "Number of Deaths",
       y = "Frequency")

jails %>%
  summarise(mean = mean(COVID.19_Deaths),
            median = median(COVID.19_Deaths))

p7 <- ggplot(data = jails, aes(x = pctpretrial)) +
  geom_histogram(binwidth = 17, color = "black", fill = "pink2") +
  labs(x = "Percent Pretrial",
       y = "Frequency") 

p8 <- ggplot(data = jails, aes(x = pctprison)) +
  geom_histogram(binwidth = 17, color = "black", fill = "red2") +
  labs(x = "Percent Convicted",
       y = "Frequency")

p9 <- ggplot(data = jails, aes(x = pctjailfromother)) +
  geom_histogram(binwidth = 17, color = "black", fill = "darkred") +
  labs(x = "Percent from Other Jail",
       y = "Frequency")

p10 <- ggplot(data = jails, aes(x = pctblackjail)) + 
  geom_histogram(binwidth = 7, fill = "lavender", color = "black") +
  labs(x = "Percent of Prisoners Black",
       y = "Frequency")

p11 <- ggplot(data = jails, aes(x = pctwhitejail)) + 
  geom_histogram(binwidth = 7, fill = "yellow2", color = "black") + 
  labs(x = "Percent of Prisoners White",
       y = "Frequency")

p12 <- ggplot(data = jails, aes(x = pctlatinxjail)) +
  geom_histogram(binwidth = 7, fill = "steelblue3", color = "black") +
  labs(x = "Percent of Prisoners Latinx", 
       y = "Frequency")

p13 <- ggplot(data = jails, aes(x = ab_avg)) +
  geom_bar(fill = "blue2", color = "black") +
  labs(x = "Above Average Percent Decrease",
       title = "Above Average Decrease (> 20%)",
       y = "Frequency")
```

```{r, echo=FALSE}
p1 | p13 

p2 | p3

p4 | (p5 / p6)

p7 | p8 | p9

p10 | p11 | p12
```

# Bivariate EDA

```{r bunch of graphs 2, echo=FALSE}

p14 <- ggplot(data = jails, aes(x = ab_avg, y = County_Profile)) +
  geom_boxplot(fill = "honeydew", color = "black") +
  labs(title = "Above Average Percent Decrease vs. County Profile",
       x = "Above Average Decrease (>20%)",
       y = "County Profile")

p15 <- ggplot(data = jails, aes(x = ab_avg, fill = Jurisdiction_Profile)) +
  geom_bar(color = "black", position = "dodge") +
  labs(title = "Above Average vs. Jurisdiction Profile",
      x = "Above Average Decrease (>20%)",
      y = "Frequency")

p16 <- ggplot(data = jails, aes(x = ab_avg, fill = urbanicity)) +
  geom_bar(color = "black", position = "dodge") +
  labs(title = "Above Average vs. Population Density",
       x = "Above Average Decrease (>20%)",
       y = "Frequency")

p17 <- ggplot(data = jails, aes(x = ab_avg, y = COVID.19_Cases)) +
  geom_boxplot(color = "black", fill = "lavender") +
  labs(title = "Above Average vs. COVID.19 Cases",
          x = "Above Average Decrease (>20%)",
       y = "Number of Cases") +
  coord_flip()

p18 <- ggplot(data = jails, aes(x = ab_avg, y = COVID.19_Deaths)) +
  geom_boxplot(color = "black", fill = "pink2") +
  labs(title = "Above Average vs. COVID.19 Cases",
       x = "Above Average Decrease (>20%)",
       y = "Number of Deaths") +
  coord_flip()

p19 <- ggplot(data = jails, aes(x = ab_avg, y = pctpretrial)) +
  geom_boxplot(color = "black", fill = "lightskyblue") +
  labs(title = "Above Average vs. Percent Pretrial",
          x = "Above Average Decrease (>20%)",
       y = "Percent Pretrial") +
  coord_flip()

p20 <- ggplot(data = jails, aes(x = ab_avg, y = pctprison)) +
  geom_boxplot(color = "black", fill = "yellow2") +
  labs(title = "Above Average vs. Percent Sentenced",
          x = "Above Average Decrease (>20%)",
       y = "Percent Sentenced") +
  coord_flip()

p21 <- ggplot(data = jails, aes(x = ab_avg, y = pctjailfromother)) +
  geom_boxplot(color = "black", fill = "steelblue3") +
  labs(title = "Above Average vs. Percent from Other Jail",
          x = "Above Average Decrease (>20%)",
       y = "Percent from Other Jails") +
  coord_flip()

p22 <- ggplot(data = jails, aes(x = ab_avg, fill = private_jail_flag)) +
  geom_bar(color = "black", position = "dodge") +
  scale_fill_manual(values = c("darkseagreen", "pink1")) +
  labs(title = "Above Average vs. Private Jail",
       x = "Above Average Decrease (>20%)",
       y = "Frequency")

p23 <- ggplot(data = jails, aes(x = ab_avg, y = pctblackjail)) +
  geom_boxplot(color = "black", fill = "violetred1") +
  labs(title = "Above Average vs. Percent Black in Prisons",
          x = "Above Average Decrease (>20%)",
       y = "Percent Black") +
  coord_flip()

p24 <- ggplot(data = jails, aes(x = ab_avg, y = pctlatinxjail)) +
geom_boxplot(color = "black", fill = "springgreen4") +
  labs(title = "Above Average vs. Percent Latinx in Prisons",
       x = "Above Average Decrease(>20%)",
       y = "Percent Latinx") + 
  coord_flip()

p25 <- ggplot(data = jails, aes(x = ab_avg, y = pctwhitejail)) +
  geom_boxplot(color = "black", fill = "antiquewhite2") +
  labs(title = "Above Average vs. Percent White in Prisons",
       x = "Above Average Decrease (>20%)",
       y = "Percent White") +
  coord_flip()
```

```{r}
p14 / (p15 | p16)

p17 | p18

p19 / p20 / p21

p21 | p22 | p23

p24 | p25
```


# Model Fitting


```{r Step-wise Strategy for Model Fitting}
model <- glm(ab_avg ~ County_Profile +
                Jurisdiction_Profile + COVID.19_Deaths + urbanicity + private_jail_flag + pctblackjail + pctlatinxjail + pctwhitejail + pctpretrial + pctprison + pctjailfromother + pctcapacity, data = jails)

tidy(model)
jails = na.omit(jails)

model_aic <- step(model, direction = "backward", trace=FALSE) 

tidy(model_aic) %>%
  select(term, estimate, p.value)
```

```{r}
modelfinal <- glm(data = jails, ab_avg ~ County_Profile + private_jail_flag + pctwhitejail + urbanicity + COVID.19_Cases)

tidy(modelfinal) %>%
  kable(digits = 3, format = "markdown")
```

- Change numbers:

$$\widehat{\mbox{Release %}} = 0.853982401 + 0.002954708~\mbox{County_Profile} + 0.172698078	~\mbox{private_jail_flag1} - 0.110669124	~\mbox{pctwhitejail} - 0.110669124	~\mbox{pctwhitejail} - 0.110669124	~\mbox{urbanicitysuburban} - 0.110669124	~\mbox{urbanicityurban} - 0.110669124	~\mbox{COVID.19_Cases	}$$

```{r augmentmodel}
model_aug <- augment(model_aic) %>%
  mutate(obs_num = row_number())
```

```{r leverage}
leverage_threshold <- 2*(8 + 1)/nrow(model_aug)

high_leverage <- model_aug %>%
  mutate(high_lev = .hat > leverage_threshold) %>%
  select(high_lev, obs_num)

high_leverage %>%
  filter(high_lev == TRUE)
```

Jefferson has more cases and deaths than most parishes

Morehouse county has a large reduction in prison population.

```{r std.residuals}
ggplot(data = model_aug, aes(x = obs_num, y = .std.resid)) +
  geom_point()

model_aug %>%
  summarise(min = min(.std.resid),
            max = max(.std.resid),
            mean = mean(.std.resid),
            median = median(.std.resid))

high_sdresid <- model_aug %>%
  mutate(high_sd = abs(.std.resid) > 2) %>%
  select(obs_num, high_sd)

high_sdresid %>%
  filter(high_sd == TRUE)
```

```{r cooksdistance}
ggplot(data = model_aug, aes(x = obs_num, y = .cooksd)) + 
  geom_point(alpha = 0.5) +
  geom_hline(yintercept = 1, color = "red")

high_cookdist <- model_aug %>%
  mutate(high_cook = .cooksd > 1) %>%
  select(obs_num, high_cook)

high_cookdist %>%
  filter(high_cook == TRUE)
```

